# Retail Sales Forecasting & Analytics Platform

## Notebook 01: Dataset Understanding

### Objective

The objective of this notebook is to understand the Rossmann Store Sales dataset before performing any preprocessing or model development.

This notebook focuses on:

- Understanding the business problem
- Understanding the provided datasets
- Loading the datasets
- Inspecting their structure
- Identifying feature types
- Detecting missing values
- Recording initial observations

No preprocessing or feature engineering is performed in this notebook.

## Business Problem

Rossmann operates thousands of drug stores across Europe. Accurate sales forecasting helps the company optimize inventory, staff scheduling, promotional planning, and revenue forecasting.

The objective of this project is to build a machine learning model capable of predicting daily sales for each Rossmann store using historical sales data and store-related information.

## Dataset Files

This project primarily uses two datasets:

- **train.csv** – Historical daily sales data containing the target variable (`Sales`).
- **store.csv** – Store-level information such as store type, assortment, competition details, and promotion participation.

Although the original Kaggle dataset also includes `test.csv` and `sample_submission.csv`, they are intended for the competition workflow. Since this project focuses on developing and evaluating machine learning models using classical ML techniques, model validation will be performed by splitting `train.csv` into training and validation sets.

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Pandas display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 2000)
pd.set_option("display.max_colwidth", None)

In [11]:
train_df = pd.read_csv("../data/raw/train.csv")
store_df = pd.read_csv("../data/raw/store.csv") #Relative path to the store.csv file

C:\Users\ragha\AppData\Local\Temp\ipykernel_40168\2835134483.py:1: DtypeWarning: Columns (0: StateHoliday) have mixed types. Specify dtype option on import or set low_memory=False.
  train_df = pd.read_csv("../data/raw/train.csv")

In [12]:
print("Train DataFrame Shape:", train_df.shape)
print("Store DataFrame Shape:", store_df.shape)

print("\n Train DataSet Preview:")
display(train_df.head(20))

print("\n Store DataSet Preview:")
display(store_df.head(20))

Train DataFrame Shape: (1017209, 9)
Store DataFrame Shape: (1115, 10)

 Train DataSet Preview:

    Store  DayOfWeek        Date  Sales  Customers  Open  Promo StateHoliday  SchoolHoliday
0       1          5  2015-07-31   5263        555     1      1            0              1
1       2          5  2015-07-31   6064        625     1      1            0              1
2       3          5  2015-07-31   8314        821     1      1            0              1
3       4          5  2015-07-31  13995       1498     1      1            0              1
4       5          5  2015-07-31   4822        559     1      1            0              1
5       6          5  2015-07-31   5651        589     1      1            0              1
6       7          5  2015-07-31  15344       1414     1      1            0              1
7       8          5  2015-07-31   8492        833     1      1            0              1
8       9          5  2015-07-31   8565        687     1      1            0              1
9      10          5  2015-07-31   7185        681     1      1            0              1
10     11          5  2015-07-31  10457       1236     1      1            0              1
11     12          5  2015-07-31   8959        962     1      1            0              1
12     13          5  2015-07-31   8821        568     1      1            0              0
13     14          5  2015-07-31   6544        710     1      1            0              1
14     15          5  2015-07-31   9191        766     1      1            0              1
15     16          5  2015-07-31  10231        979     1      1            0              1
16     17          5  2015-07-31   8430        946     1      1            0              1
17     18          5  2015-07-31  10071        936     1      1            0              1
18     19          5  2015-07-31   8234        718     1      1            0              1
19     20          5  2015-07-31   9593        974     1      1            0              0

 Store DataSet Preview:

    Store StoreType Assortment  CompetitionDistance  CompetitionOpenSinceMonth  CompetitionOpenSinceYear  Promo2  Promo2SinceWeek  Promo2SinceYear     PromoInterval
0       1         c          a               1270.0                        9.0                    2008.0       0              NaN              NaN               NaN
1       2         a          a                570.0                       11.0                    2007.0       1             13.0           2010.0   Jan,Apr,Jul,Oct
2       3         a          a              14130.0                       12.0                    2006.0       1             14.0           2011.0   Jan,Apr,Jul,Oct
3       4         c          c                620.0                        9.0                    2009.0       0              NaN              NaN               NaN
4       5         a          a              29910.0                        4.0                    2015.0       0              NaN              NaN               NaN
5       6         a          a                310.0                       12.0                    2013.0       0              NaN              NaN               NaN
6       7         a          c              24000.0                        4.0                    2013.0       0              NaN              NaN               NaN
7       8         a          a               7520.0                       10.0                    2014.0       0              NaN              NaN               NaN
8       9         a          c               2030.0                        8.0                    2000.0       0              NaN              NaN               NaN
9      10         a          a               3160.0                        9.0                    2009.0       0              NaN              NaN               NaN
10     11         a          c                960.0                       11.0                    2011.0       1              1.0           2012.0   Jan,Apr,Jul,Oct
11     12         a          c               1070.0                        NaN                       NaN       1             13.0           2010.0   Jan,Apr,Jul,Oct
12     13         d          a                310.0                        NaN                       NaN       1             45.0           2009.0   Feb,May,Aug,Nov
13     14         a          a               1300.0                        3.0                    2014.0       1             40.0           2011.0   Jan,Apr,Jul,Oct
14     15         d          c               4110.0                        3.0                    2010.0       1             14.0           2011.0   Jan,Apr,Jul,Oct
15     16         a          c               3270.0                        NaN                       NaN       0              NaN              NaN               NaN
16     17         a          a                 50.0                       12.0                    2005.0       1             26.0           2010.0   Jan,Apr,Jul,Oct
17     18         d          c              13840.0                        6.0                    2010.0       1             14.0           2012.0   Jan,Apr,Jul,Oct
18     19         a          c               3240.0                        NaN                       NaN       1             22.0           2011.0  Mar,Jun,Sept,Dec
19     20         d          a               2340.0                        5.0                    2009.0       1             40.0           2014.0   Jan,Apr,Jul,Oct

In [13]:
train_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1017209 entries, 0 to 1017208
Data columns (total 9 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   Store          1017209 non-null  int64
 1   DayOfWeek      1017209 non-null  int64
 2   Date           1017209 non-null  str
 3   Sales          1017209 non-null  int64
 4   Customers      1017209 non-null  int64
 5   Open           1017209 non-null  int64
 6   Promo          1017209 non-null  int64
 7   StateHoliday   1017209 non-null  object
 8   SchoolHoliday  1017209 non-null  int64
dtypes: int64(7), object(1), str(1)
memory usage: 69.8+ MB

In [16]:
train_df.describe()

              Store     DayOfWeek         Sales     Customers          Open         Promo  SchoolHoliday
count  1.017209e+06  1.017209e+06  1.017209e+06  1.017209e+06  1.017209e+06  1.017209e+06   1.017209e+06
mean   5.584297e+02  3.998341e+00  5.773819e+03  6.331459e+02  8.301067e-01  3.815145e-01   1.786467e-01
std    3.219087e+02  1.997391e+00  3.849926e+03  4.644117e+02  3.755392e-01  4.857586e-01   3.830564e-01
min    1.000000e+00  1.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   0.000000e+00
25%    2.800000e+02  2.000000e+00  3.727000e+03  4.050000e+02  1.000000e+00  0.000000e+00   0.000000e+00
50%    5.580000e+02  4.000000e+00  5.744000e+03  6.090000e+02  1.000000e+00  0.000000e+00   0.000000e+00
75%    8.380000e+02  6.000000e+00  7.856000e+03  8.370000e+02  1.000000e+00  1.000000e+00   0.000000e+00
max    1.115000e+03  7.000000e+00  4.155100e+04  7.388000e+03  1.000000e+00  1.000000e+00   1.000000e+00

In [17]:
train_df.describe(include="object")

C:\Users\ragha\AppData\Local\Temp\ipykernel_40168\159040709.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  train_df.describe(include="object")

              Date StateHoliday
count      1017209      1017209
unique         942            5
top     2015-07-31            0
freq          1115       855087

In [20]:
train_df["StateHoliday"].value_counts()

StateHoliday
0    855087
0    131072
a     20260
b      6690
c      4100
Name: count, dtype: int64

In [21]:
train_df["Open"].value_counts()

Open
1    844392
0    172817
Name: count, dtype: int64

In [30]:
train_df.duplicated().sum()

np.int64(0)

In [25]:
store_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1115 entries, 0 to 1114
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Store                      1115 non-null   int64
 1   StoreType                  1115 non-null   str
 2   Assortment                 1115 non-null   str
 3   CompetitionDistance        1112 non-null   float64
 4   CompetitionOpenSinceMonth  761 non-null    float64
 5   CompetitionOpenSinceYear   761 non-null    float64
 6   Promo2                     1115 non-null   int64
 7   Promo2SinceWeek            571 non-null    float64
 8   Promo2SinceYear            571 non-null    float64
 9   PromoInterval              571 non-null    str
dtypes: float64(5), int64(2), str(3)
memory usage: 87.2 KB

In [26]:
store_df.describe()

            Store  CompetitionDistance  CompetitionOpenSinceMonth  CompetitionOpenSinceYear       Promo2  Promo2SinceWeek  Promo2SinceYear
count  1115.00000          1112.000000                 761.000000                761.000000  1115.000000       571.000000       571.000000
mean    558.00000          5404.901079                   7.224704               2008.668857     0.512108        23.595447      2011.763573
std     322.01708          7663.174720                   3.212348                  6.195983     0.500078        14.141984         1.674935
min       1.00000            20.000000                   1.000000               1900.000000     0.000000         1.000000      2009.000000
25%     279.50000           717.500000                   4.000000               2006.000000     0.000000        13.000000      2011.000000
50%     558.00000          2325.000000                   8.000000               2010.000000     1.000000        22.000000      2012.000000
75%     836.50000          6882.500000                  10.000000               2013.000000     1.000000        37.000000      2013.000000
max    1115.00000         75860.000000                  12.000000               2015.000000     1.000000        50.000000      2015.000000

In [27]:
store_df.describe(include="object")

C:\Users\ragha\AppData\Local\Temp\ipykernel_40168\471526336.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  store_df.describe(include="object")

       StoreType Assortment    PromoInterval
count       1115       1115              571
unique         4          3                3
top            a          a  Jan,Apr,Jul,Oct
freq         602        593              335

In [29]:
store_df.duplicated().sum()

np.int64(0)

In [36]:
train_df["Store"].nunique()

1115

In [37]:
store_df["Store"].nunique()

1115

In [38]:
set(train_df["Store"]) == set(store_df["Store"])

True